-- Generated by pipeline/lore/voicepack.py - do not edit by hand.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
local c = P.clips
c["npc:hogger"] = "deadbeef0001"
c["odd\"id\\x"] = "123456789abc"
c["subzone:goldshire"] = "000000000000"
c["zone:stormwind"] = "a1b2c3d4e5f6"
c["zone:stormwind#faq1"] = "0f0f0f0f0f0f"
