-- Generated by pipeline/lore/voicepack.py - do not edit by hand.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
local c = P.clips
P.ext = "ogg"
c["zone:durotar"] = "fedcbafedcba"
c["zone:durotar#faq2"] = "abcdefabcdef"
