local P = LoreForeverPacks.Begin("LoreForever_Voice_Default_Horde")
P.transportVersion = 1
P.transport = {}
P.transport["npc:anastasia-hartwell"] = {
  hash = "b4d21f",
  fullHash = "c67820",
  text = "Anastasia Hartwell. Anastasia Hartwell is a prominent Forsaken mage trainer residing in the Magic Quarter of the Undercity. She guides fledgling and developing spellcasters in mastering the arcane arts and oversees vital magical research and field missions across Lordaeron and beyond. Standing within the dark, echoing chambers of the Undercity's Magic Quarter, Anastasia Hartwell instructs Forsaken and Horde mages in channeling arcane energies. Though the kingdom of Lordaeron fell to ruin, former human practitioners like Anastasia have preserved their scholarly traditions in undeath. She maintains that magic demands strict discipline, warning any traveler she meets that careless incantations will quickly consume the untrained. Beyond fundamental spell instruction, Anastasia directs promising students toward vital field investigations. She dispatches mages into Tirisfal Glades, including the blighted grounds of the Balnir Farmstead and ruined alchemist workshops, to recover lost reagents and salvage remnants of forgotten arcane lore. Through her tasks, practitioners learn that securing magical dominance requires braving the hazardous ruins of their former homeland. Anastasia's connections reach well beyond the borders of Tirisfal. As Horde spellcasters grow in proficiency, she coordinates with fellow trainers in distant lands, such as Deino in Orgrimmar, and directs advanced students toward solitary masters like Tabetha in the swamplands of Dustwallow Marsh. Her guidance ensures that Forsaken mages remain woven into the wider tapestry of the Horde's magical pursuits.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_anastasia-hartwell-9fdada84232175c45f0e/1-0000.mp3", duration = 95.477551, start = 0},
  },
}
P.transport["npc:aramis-hammerhand"] = {
  hash = "0e57d9",
  fullHash = "097c50",
  text = "Aramis Hammerhand. Aramis Hammerhand is an undead holy warrior situated within the desecrated chapel of Deathknell. As a Forsaken paladin trainer, he instructs newly risen dead who seek to reclaim their bond with the Holy Light. Walking this path in undeath requires immense discipline, as wielding such radiant energy inflicts agonizing pain upon their decayed flesh. Standing within the somber walls of Deathknell's chapel, Aramis Hammerhand represents an anomaly among the recently awakened Forsaken. In life, many citizens of Lordaeron answered the call of the Silver Hand, only to perish when the Scourge swept across the north. Aramis survived the fall only to be raised into undeath, yet he chose not to abandon the martial and spiritual teachings of his former existence. Now, he offers guidance to others who refuse to surrender their devotion. For an undead being, channeling the Holy Light is an ordeal of supreme willpower. The power burns necrotic flesh and reawakens long-dead nerves to excruciating pain. Aramis instructs his initiates that holding to this faith requires enduring continual torment. Through tasks like 'A Difficult Path' and 'Rediscovering the Light', he demands that young paladins confront the physical and spiritual costs of wielding a force inherently opposed to their present nature.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_aramis-hammerhand-77986bfcd9e9069ea01c/1-0000.mp3", duration = 77.7404082, start = 0},
  },
}
P.transport["npc:arugal"] = {
  hash = "b4d729",
  fullHash = "6486d8",
  text = "Arugal. Archmage Arugal is a former wizard of Dalaran and Gilneas who unleashed the feral worgen upon Lordaeron. Overcome by madness and grief, he now rules from the heights of Shadowfang Keep, treating the savage beasts as his beloved children while menacing all of Silverpine Forest. Before the fall of Lordaeron, Arugal was a member of the Kirin Tor, though some peers like Dalar Dawnweaver dismissed him as a charlatan whose weak spellcraft relied heavily on enchanted trinkets. When the Scourge swept across the north during the Third War, Arugal sought a weapon powerful enough to stem the tide. Drawing upon the esoteric research of the late Dalaran mage Ur, Arugal pierced the veil between realms and summoned the worgen into the mortal world. The ravenous beasts tore through the undead legions as intended, but their feral ferocity could not be contained, and their savage hunger swiftly turned against innocent mortals. The summoned horrors slaughtered the Gilnean soldiers stationed outside the Greymane Wall and spread their dreadful affliction through Gilneas. Some of the beasts then besieged the ancestral seat of Baron Silverlaine, and the keep fell swiftly to claws and fangs, its lord and retainers slain in the massacre. Rather than flee from his monstrous creation, Arugal's mind fractured under the weight of guilt, and he adopted the beasts as his own offspring. Renaming the fortress Shadowfang Keep, Arugal entrenched himself within its ramparts, surrounded by ghostly victims and loyal hound-packs.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_arugal-e6085b44055df71121c8/1-0000.mp3", duration = 90.122449, start = 0},
  },
}
P.transport["npc:baine-bloodhoof"] = {
  hash = "f3766e",
  fullHash = "369bb3",
  text = "Baine Bloodhoof. Baine Bloodhoof is the son of High Chieftain Cairne Bloodhoof and the acting protector of Bloodhoof Village in Mulgore. While his father governs the tribes from the towering heights of Thunder Bluff, Baine directly oversees local defense, investigating encroaching industrial exploitation and defending against feral predators. He serves as an essential bridge between youthful tauren braves and the ancestral wisdom of his clan. Born to Cairne and the late Tamaala, Baine spent his youth traveling alongside his nomadic people before they claimed the rich grasslands of Mulgore. His early life was marked by the ever-present threat of the centaur clans. Shortly after the Third War, a centaur warband under Khiragg captured young Baine, plunging Cairne into a grief-stricken stupor that nearly shattered the newly founded settlements. It was only through the courage of the champion Rexxar that Baine was liberated from captivity. That rescue restored Cairne's spirit, allowing the tauren to stand with Thrall's Horde against the invading Kul Tirans and secure their foothold on the continent. Rather than lingering in the relative comfort of the capital mesas, Baine chooses to reside among his kin in Bloodhoof Village. As Cairne advances in age, Baine carries an increasing burden of stewardship, representing the next generation of tauren leadership. He directs braves and visiting allies to combat the unruly Palemane gnolls who pester the borders, and keeps a watchful eye on suspicious outside influences threatening Mulgore's natural balance. Whenever Cairne departs the capital on state affairs, Baine steps forward as the acting leader for the united tribes. Beyond territorial border clashes, Baine faces modern encroachers unconcerned with spiritual balance. To the east, the goblin Venture Company cuts deep into the sacred landscape, while dwarven prospectors from Bael Modan dig into ancestral soil at the Bael'dun Digsite. Baine advocates for a firm yet measured response: attempting to warn the miners and destroy their destructive equipment rather than rushing into senseless bloodshed. He warns that the dwarves' violent digging is hurting the spirits of the earth, though the miners refuse to listen.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_baine-bloodhoof-0c7b8d2d29368141e2a7/1-0000.mp3", duration = 131.134694, start = 0},
  },
}
P.transport["npc:bethor-iceshard"] = {
  hash = "a5695c",
  fullHash = "d8984b",
  text = "Bethor Iceshard. Bethor Iceshard is a powerful Forsaken mage based in the Magic Quarter of the Undercity. Presiding over the arcane and shadow practitioners within the Temple of the Damned, he commands considerable authority in Sylvanas's realm. Beneath his chilly demeanor lies a past entwined with old friends torn apart by the Scourge. Standing within the Temple of the Damned, Bethor Iceshard oversees the practitioners of the arcane arts and shadow magic in the Undercity. Respected and feared for his intellect and icy resolve, Bethor wields sufficient political and magical weight to give direct instructions to provincial magistrates across Lordaeron. He directs agents of the Forsaken to secure valuable grimoires, investigate arcane anomalies, and stamp out rival powers that threaten the Undercity's dominion. Before the Third War devastated Lordaeron, Bethor was a mortal apprentice studying magic alongside two close companions: Gunther Arcanus and Thule Ravenclaw. As a testament to their fellowship, the three students wove their practice wands together. The Scourge shattered that bond entirely. When death and dark magic swept across the kingdom, Thule Ravenclaw willfully surrendered his soul to the Lich King, Gunther perished and rose on an isolated island in Brightwater Lake, and Bethor succumbed only to later break free as Forsaken.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_bethor-iceshard-931be89a459dfcecd334/1-0000.mp3", duration = 79.6734694, start = 0},
  },
}
P.transport["npc:brewmaster-drohn"] = {
  hash = "04d8ab",
  fullHash = "db1f87",
  text = "Brewmaster Drohn. Brewmaster Drohn is an orcish brewmaster living just uphill from the bustling port of Ratchet. Having learned the art of exotic fermentation through ties connected to the legendary wandering pandaren Chen Stormstout, Drohn crafts potent beverages on the arid frontier of the Barrens. Adventurers who discover discarded kegs across Kalimdor often find themselves directed straight to his porch. Overlooking the goblin docks of Ratchet sits Brewmaster Drohn, an orc who has devoted his craft to the science of brewing rather than simple combat. Running Drohn's Distillery from his hillside home, he operates peacefully within the neutral haven established by Gazlowe's Steamwheedle cartel. While most orcs settle for coarse grog or simple spirits, Drohn's work involves rare ingredients, refined balances of flavor, and techniques rarely practiced among his kin. Drohn's craft is heavily shaped by Chen Stormstout, the famed pandaren wanderer who fought alongside Rexxar and the Horde during the founding of Durotar. Drohn's mentor studied directly under Chen, learning the guarded secrets of Stormstout brews, and Chen himself later instructed Drohn in crafting Trogg Ale. When travelers stumble across Chen's distinct, discarded kegs in the wilds, Drohn is the sole local authority capable of identifying the ingredients and recreating the wanderer's potent concoctions.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_brewmaster-drohn-4ef60ffa3febe130dc0a/1-0000.mp3", duration = 84.7673469, start = 0},
  },
}
P.transport["npc:brine"] = {
  hash = "c7576d",
  fullHash = "a88505",
  text = "Brine. Brine is an orc shaman residing in the arid hills of Blackthorn Ridge in the southern Barrens. As an expert on the spirits of water, she guides shaman initiates along the spiritual path to commune with the tides and earn their Water Totem. Perched upon a windswept hill in northern Blackthorn Ridge, Brine lives far from the bustling trading posts of the Barrens. Despite the dry savannas surrounding her, she has dedicated her life to understanding the fluid and fickle element of water. Shaman across the Horde are directed to seek her wisdom once they have mastered earth and fire, for water requires patience and perspective that few understand as deeply as she does. In her younger years, Brine marched alongside her orc companions across the Hillsbrad Foothills, taking part in battles against human settlements. During that arduous campaign, she found herself in Tarren Mill, where she encountered a humble well fed by pure, fresh spring water. That well remained in her memory as a symbol of life persisting amidst devastation, reinforcing a lesson taught to her as a child: even in the darkest times of sorrow, a small token of hope can still be found.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_brine-24d2dcf89465aba1b449/1-0000.mp3", duration = 68.7804082, start = 0},
  },
}
P.transport["npc:cairne-bloodhoof"] = {
  hash = "5800f5",
  fullHash = "b733a6",
  text = "Cairne Bloodhoof. Cairne Bloodhoof is the venerable High Chieftain of the united tauren tribes and ruler of Thunder Bluff. A towering warrior of immense wisdom, he bound the fate of the tauren to Thrall's Horde after the orcs aided his people in escaping extinction at the hands of the centaur. For generations, the tauren lived as wandering nomads across the Barrens, continually hunted and driven toward extinction by savage centaur marauders. When Thrall and his orcs arrived on the shores of Kalimdor, Cairne recognized a rare nobility in them. Thrall offered military protection, escorting Cairne's desperate caravan across the plains to the safety of Mulgore in exchange for guidance to the Oracle at Stonetalon Peak. Settling upon the towering mesas of Thunder Bluff, Cairne finally established a permanent, unified home for all tauren tribes. Indebted to Thrall, Cairne followed the orcs to Stonetalon Peak and fought side by side with the Horde and Jaina Proudmoore's humans against the Burning Legion during the Third War. Later, when Admiral Daelin Proudmoore invaded Durotar, Cairne personally took up his ancestral runespear once more to fight alongside Rexxar after his captured son, Baine, was safely recovered. Today, Cairne stands as one of the Horde's most respected elders and Thrall's closest confidant, offering calm council against reckless warmongering.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_cairne-bloodhoof-9efeca7ffcec65a5a46f/1-0000.mp3", duration = 83.0955102, start = 0},
  },
}
P.transport["npc:canaga-earthcaller"] = {
  hash = "64c706",
  fullHash = "310f0a",
  text = "Canaga Earthcaller. Canaga Earthcaller is a Darkspear troll shaman stationed in the sunbaked Valley of Trials. He instructs novice Horde shamans in communing with the spirits of the land and obtaining their first elemental totems. Beyond ritual guidance, he keeps a watchful eye on wounded scouts and emerging threats near the Den. Perched on the red bluffs of the Valley of Trials, Canaga Earthcaller serves as one of the very first spiritual guides for Darkspear trolls and orcs who walk the path of the shaman. While many trainers focus strictly on martial readiness, Canaga teaches newcomers how to quiet their minds and listen to the rumblings of Kalimdor itself, preparing the earth sapta necessary to commune with the spirits. Before any fledgling shaman can truly channel the elemental fury of the earth, they must prove their respect and resolve to the spirits. Canaga directs initiates to gather sacred reagents and journey to the local spirit rock in Durotar. Through his guidance, novices drink the earth sapta, behold the elemental spirits firsthand, and earn their Earth Totem. Canaga does not merely dwell on esoteric rituals; he remains attuned to the valley's immediate dangers. When his friend Hana'zua heads north into the valley where the scorpids hunt and fails to return, Canaga directs capable travelers to search for him, ensuring the tribe's scouts are not left to perish in the wilderness.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_canaga-earthcaller-0eecc0c0c11e45395b5d/1-0000.mp3", duration = 83.1738776, start = 0},
  },
}
P.transport["npc:chief-hawkwind"] = {
  hash = "9d1df3",
  fullHash = "76a931",
  text = "Chief Hawkwind. Chief Hawkwind is the tribal leader of Camp Narache, the proving grounds nestled in the Red Cloud Mesa of Mulgore. Responsible for guiding the youth of the Shu'halo, he mentors new adventurers as they embark on their traditional rites of passage. Under his watchful gaze, young braves learn humility, respect for the land, and the strength needed to protect their people. Standing at the heart of Camp Narache, Chief Hawkwind carries the solemn responsibility of preparing the next generation of tauren for the wider world. Red Cloud Mesa serves as a sheltered haven where fledgling hunters, shamans, druids, and warriors undertake the ancient Rites of the Earthmother. Hawkwind oversees these customs, ensuring that every youth learns duty and endurance before venturing beyond the safety of the mesa. Hawkwind's lessons begin with humility rather than martial glory. He sends initiates on simple chores, such as fetching clean spring water, to instill reverence for the natural world and their elders. Only after demonstrating a humble heart are braves guided toward tests of martial prowess, culminating in trials that test their resolve against the aggressive Bristleback quilboar encroaching upon the ancestral plains. Beyond his role as a mentor, Chief Hawkwind must reckon with rising dangers right at his camp's doorstep. The Bristleback tribe has grown increasingly bold, pressing hard against the perimeter of Red Cloud Mesa. Hawkwind coordinates the defense of the settlement, tasking newly proven braves with blunting the quilboar assaults to ensure the sacred training grounds remain secure.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_chief-hawkwind-9cba16ffab2522940835/1-0000.mp3", duration = 93.8057143, start = 0},
  },
}
P.transport["npc:coleman-farthing"] = {
  hash = "e6c443",
  fullHash = "8a1640",
  text = "Coleman Farthing. Coleman Farthing is a bitter Forsaken survivor residing in the Gallows' End Tavern in Brill. In life, he worked for the wealthy Agamand dynasty at their extensive flour mills in northern Tirisfal. Convinced to stay and defend the estate against the Scourge, he died alongside his fellow laborers, and now dedicates his undeath to exacting vengeance on his former masters. Before the Third War, Coleman Farthing earned an honest living as a laborer at the Agamand Mills, the largest milling and agricultural operation in Tirisfal Glades. When the Scourge poured across Lordaeron, the aristocratic Agamand family refused to flee their valuable lands. Instead, they urged their household and laborers to take up arms alongside them, promising they could hold the farmsteads against the undead horde. Coleman and his fellow workers stayed, believing their masters—a decision that cost every last one of them their lives. Raised into undeath only to break free under the banner of the Forsaken, Coleman harbors a burning hatred for the Agamands. Rather than blaming only the Scourge, he blames the sheer hubris and greed of his employers for tricking their staff into an impossible last stand. Now loitering in Brill's tavern, Coleman enlists Horde champions to march into the blighted mills, cut down the risen Agamand kin, and shatter the heirloom relics housed within their family crypt so that their legacy is utterly erased.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_coleman-farthing-ea023f9e6ad9b2386b6f/1-0000.mp3", duration = 85.7338776, start = 0},
  },
}
P.transport["npc:dalar-dawnweaver"] = {
  hash = "4185b6",
  fullHash = "0acc8b",
  text = "Dalar Dawnweaver. Dalar Dawnweaver is a former archmage of Dalaran who now serves the Forsaken at the Sepulcher in Silverpine Forest. Slain during the Scourge's destruction of the magi's city and later freed from the Lich King's control, he turns his magical intellect toward dissecting regional threats. From the shadows of the tomb, he directs efforts to understand Dalaran's lingering presence and undo the madness of Archmage Arugal. In life, Dalar Dawnweaver held high rank among the Kirin Tor, walking the halls of the Violet Citadel when Dalaran was a pinnacle of arcane mastery. His mortal life ended when the Scourge sacked the city to pave the way for Archimonde's summoning. Reanimated into the mindless thrall of the Lich King, Dalar broke free alongside Lady Sylvanas Windrunner when the Scourge's grip faltered. Now stationed at the Sepulcher, he retains the piercing intellect of an archmage, turned entirely toward safeguarding the Forsaken realm. Silverpine Forest is caught between multiple perils, and Dalar serves as the Sepulcher's arcane strategist. To the south, Dalaran wizards occupy Ambermill under a protective dome, meddling in matters Dalar seeks to uncover and disrupt. Even closer looms Shadowfang Keep and the feral worgen loosed upon the woods. Dalar possesses intimate knowledge of his former colleague, Archmage Arugal, and meticulously orchestrates campaigns to neutralize Arugal's beastly creations before they overrun the region.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_dalar-dawnweaver-a9b9fef51e87a83888c2/1-0000.mp3", duration = 90.6187755, start = 0},
  },
}
P.transport["npc:darsok-swiftdagger"] = {
  hash = "6cf2c8",
  fullHash = "1b245e",
  text = "Darsok Swiftdagger. Darsok Swiftdagger is an orc warrior and scout stationed at the Crossroads in the heart of the Barrens. Known for his fierce hatred of harpies, he directs Horde adventurers north into the Dry Hills to break the avian matriarchy harassing travelers and settlements. He maintains ties across the plains, serving as a trusted contact for Witch Doctor Jin'Zil in Malaka'jin. Amid the bustling hub of the Crossroads, Darsok Swiftdagger keeps a sharp eye on the threats creeping out of the northern scrubland. The trade artery connecting Durotar, Mulgore, and the northern reaches is under constant siege, not only from raiders and centaur, but from organized aerial hunters. Darsok focuses his wrath on the Witchwing harpies, whose roosts in the Dry Hills northwest of the Forgotten Pools directly threaten northern caravans. While his immediate duties center around harpy eradication, Darsok Swiftdagger serves as an important point of contact within the Horde network. He maintains correspondence with Witch Doctor Jin'Zil, the enigmatic troll residing at Malaka'jin on the border of the Stonetalon Mountains. Messages and intelligence carried through Darsok help ensure that outlying enclaves stay informed of developments across the central plains.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_darsok-swiftdagger-5f2f83430b7dcd798f7e/1-0000.mp3", duration = 76.1469388, start = 0},
  },
}
P.transport["npc:deathguard-dillinger"] = {
  hash = "cf2185",
  fullHash = "f5d4af",
  text = "Deathguard Dillinger. Deathguard Dillinger is a Forsaken sentry stationed in Brill within Tirisfal Glades. Standing watch over the town's perimeter, he directs newly arrived undead toward necessary services and tasks recruits with keeping the local Scourge remnants at bay. As a member of the Forsaken Deathguard, Dillinger stands at the entrance of Brill, serving as both a frontline protector and an orienting guide for travelers emerging from Deathknell. He provides directions to town amenities such as the inn, the town hall, and local trainers, helping newly awakened undead navigate their new reality under the Dark Lady's rule. Dillinger actively enlists capable adventurers to purge lingering mindless Scourge from the nearby farms and mills. Through assignments like cullling rotting ghouls and reclaiming infested facilities, he seeks to establish a buffer zone of security around Brill, ensuring the fledgling Forsaken settlements can endure against unending undead predation.",
  ["1"] = {
    {file = "Audio/Transport/full_npc_deathguard-dillinger-53a5710aad237e6b3ce6/1-0000.mp3", duration = 59.1934694, start = 0},
  },
}
