-- Generated by pipeline/lore/compile_lua.py --lang ukUA - do not edit by hand.
-- Sources: data/i18n/ukUA. Lore text adapted from warcraft.wiki.gg (CC BY-SA 4.0); the core add-on's src fields name the articles.
local P = LoreForeverPacks.Begin("LoreForever_Lang_ukUA")
