-- Generated by lore.contributor_edition; do not edit.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
P.edition = {["api"]=1,["id"]="densuad-esES",["peer"]="LoreForever_Edition_Densuad_esES_Text",["version"]="d16f932949280831634380a05a0046b1feda0f5d8c46182d2cde90b0bd6057d1"}
