#!/usr/bin/env python3
"""Portable paired-edition validation and ZIP builder; Python standard library only.

The audited manifest binds exact contributed files and the immutable core Data tree.
No Lua execution, private pipeline, original intake, provider, or network is needed.
"""
import argparse
from collections import Counter
import hashlib
import json
import math
import os
from pathlib import Path
import re
import tempfile
import zipfile

EDITION_ID = "densuad-esES"
TEXT_NAME = "LoreForever_Edition_Densuad_esES_Text"
AUDIO_NAME = "LoreForever_Edition_Densuad_esES_Audio"
SCHEMA = "lore-contributor-edition-v1"
ROOT = Path(__file__).resolve().parents[1]
MANIFEST = "Manifest.json"
SHA = re.compile(r"[0-9a-f]{64}")
HEADER = "-- Generated by lore.contributor_edition; do not edit.\n"
LFS_HEADER = b"version https://git-lfs.github.com/spec/v1"


def split_id(rid):
    key, sep, index = rid.partition("#faq")
    return key, int(index) if sep else None


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate manifest key: " + key)
        result[key] = value
    return result


def core_source(addon_root):
    """Conservative portable proof: all core Data Lua/XML files, including load files."""
    core = Path(addon_root) / "LoreForever"
    data = core / "Data"
    if core.is_symlink() or data.is_symlink() or not data.is_dir():
        raise ValueError("missing or unsafe core Data directory")
    files = {}
    for path in sorted(data.rglob("*")):
        if path.is_symlink():
            raise ValueError("symlink in core source")
        if path.is_file() and path.suffix in (".lua", ".xml"):
            rel = path.relative_to(core).as_posix()
            if not re.fullmatch(r"Data/(?:[A-Za-z0-9_-]+/)*[A-Za-z0-9_-]+\.(?:lua|xml)", rel):
                raise ValueError("unsafe core source filename")
            files[rel] = {"sha256": file_sha(path), "bytes": path.stat().st_size}
    if "Data/Data.xml" not in files or not any(p.endswith(".lua") for p in files):
        raise ValueError("incomplete core source inventory")
    return {"algorithm": "sha256", "files": files, "fingerprint": sha256(canonical(files))}


def validate_core_source(addon_root, manifest):
    proof = manifest.get("core_source")
    if not isinstance(proof, dict) or proof != core_source(addon_root):
        raise ValueError("stale underlying English source: core Data fingerprint/files differ")

def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")

def sha256(data):
    return hashlib.sha256(data).hexdigest()

def file_sha(path):
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()

def lua(value):
    """Lua 5.1 literals without stripping or normalizing contributor prose."""
    if isinstance(value, str):
        s = value.replace("\\", "\\\\").replace('"', '\\"')
        s = re.sub(r"[\x00-\x1f\x7f]", lambda m: "\\%03d" % ord(m[0]), s)
        return '"' + s + '"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if not math.isfinite(value):
            raise ValueError("non-finite Lua number")
        return repr(value)
    if isinstance(value, list):
        return "{" + ",".join(lua(v) for v in value) + "}"
    if isinstance(value, dict):
        return "{" + ",".join("[" + lua(k) + "]=" + lua(v) for k, v in sorted(value.items())) + "}"
    raise ValueError("unsupported Lua literal")

def _title(text, key):
    title, separator, _ = text.partition(". ")
    if separator and 0 < len(title) <= 120 and not re.search(r"[\x00-\x1f|{}<>]", title):
        return title
    return key

def _metadata(toc):
    result = {}
    for line in toc.splitlines():
        if line.startswith("## "):
            key, sep, value = line[3:].partition(":")
            if not sep or key in result:
                raise ValueError("malformed or duplicate TOC metadata")
            result[key] = value.strip()
    return result

def _core_metadata(addon_root):
    path = Path(addon_root) / "LoreForever/LoreForever.toc"
    if path.is_symlink():
        raise ValueError("symlink core TOC")
    toc = path.read_text(encoding="utf-8")
    metadata = _metadata(toc)
    if not re.fullmatch(r"\d+\.\d+\.\d+", metadata.get("Version", "")):
        raise ValueError("core version must be an explicit semantic version")
    return metadata["Interface"], metadata["Version"]

def _edition(peer, version):
    return {"id": EDITION_ID, "version": version, "peer": peer, "api": 1}

def _toc(name, peer, kind, manifest):
    return (f"## Interface: {manifest['interface']}\n"
            f"## Title: Lore Forever — Densuad español ({'texto' if kind == 'edition-text' else 'voz'})\n"
            "## Notes: Optional paired contributor edition.\n## Author: Densuad\n"
            f"## Version: {manifest['core_version']}\n## Dependencies: LoreForever\n## LoadOnDemand: 1\n"
            f"## X-LoreForever-Pack: {kind}\n## X-LoreForever-Locale: esES\n"
            "## X-LoreForever-Format: 1\n## X-LoreForever-Credit: Densuad\n"
            f"## X-LoreForever-CoreVersion: {manifest['core_version']}\n"
            f"## X-LoreForever-Edition: {EDITION_ID}\n"
            f"## X-LoreForever-EditionVersion: {manifest['version']}\n"
            f"## X-LoreForever-EditionPeer: {peer}\n## X-LoreForever-EditionAPI: 1\nEdition.xml\n")

def declared_files(manifest):
    """Pure serialization: same manifest gives byte-identical TOCs and Lua."""
    result = {}
    for name, peer, kind in [(TEXT_NAME, AUDIO_NAME, "edition-text"), (AUDIO_NAME, TEXT_NAME, "edition-voice")]:
        result[f"{name}/{name}.toc"] = _toc(name, peer, kind, manifest).encode("utf-8")
        prefix = HEADER + "local name = ...\nlocal P = LoreForeverPacks and LoreForeverPacks.Begin(name)\nif not P then return end\n"
        scripts = ["Edition.lua"]
        result[f"{name}/Edition.lua"] = (prefix + "P.edition = " + lua(_edition(peer, manifest["version"])) + "\n").encode("utf-8")
        payload = manifest["text_data"] if kind == "edition-text" else manifest["audio_data"]
        for field, values in sorted(payload.items()):
            # Small chunks stay comfortably below Lua 5.1's constant limit.
            items = sorted(values.items())
            for start in range(0, max(1, len(items)), 40):
                filename = field + f"{start // 40 + 1:03d}.lua"
                scripts.append(filename)
                lines = [prefix, "P." + field + " = P." + field + " or {}\n", "local t = P." + field + "\n"]
                lines.extend("t[" + lua(k) + "] = " + lua(v) + "\n" for k, v in items[start:start + 40])
                result[f"{name}/{filename}"] = "".join(lines).encode("utf-8")
        result[f"{name}/Edition.xml"] = ("<Ui xmlns=\"http://www.blizzard.com/wow/ui/\">\n" +
            "".join(f'  <Script file="{s}"/>\n' for s in scripts) + "</Ui>\n").encode("utf-8")
    return result

def _counts(records, entries):
    return {"contributed_records": len(records), "contributed_entries": sum(r["faq_index"] is None for r in records),
            "contributed_faq_answers": sum(r["faq_index"] is not None for r in records),
            "compatible_current_records": sum(r["source_status"] == "accepted" for r in records),
            "compatible_current_entries": len(entries), "compatible_current_faq_answers": sum(len(e["faq"]) for e in entries.values()),
            "deferred_source_records": sum(r["source_status"] != "accepted" for r in records),
            "recordings": sum(r["published_audio"] for r in records),
            "recording_bytes": sum(r["audio_bytes"] for r in records if r["published_audio"]),
            "unavailable_script_pairings": sum(not r["exact_audio_pair"] for r in records),
            "readable_without_audio": sum(r["source_status"] == "accepted" and not r["published_audio"] for r in records)}

def validate_pair(addon_root, edition_id=EDITION_ID):
    """Validate exact paired declarations, core source files, and hydrated MP3s.

    Returns the checked manifest. Raises ValueError on incompatibility. No writes.
    The core must be present; neither private intake nor provider access is needed.
    """
    if edition_id != EDITION_ID:
        raise ValueError("unsupported edition ID")
    addon_root = Path(addon_root)
    paths = [addon_root / name for name in (TEXT_NAME, AUDIO_NAME)]
    if any(p.is_symlink() or (p / MANIFEST).is_symlink() for p in paths):
        raise ValueError("symlink component/manifest")
    blobs = [(p / MANIFEST).read_bytes() for p in paths]
    if blobs[0] != blobs[1]:
        raise ValueError("mixed component manifests or versions")
    manifest = json.loads(blobs[0], object_pairs_hook=_unique_object)
    if manifest.get("schema") != SCHEMA or manifest.get("id") != edition_id or type(manifest.get("api")) is not int or manifest["api"] != 1:
        raise ValueError("malformed edition manifest/API")
    logical = {k: v for k, v in manifest.items() if k not in ("version", "files")}
    if not SHA.fullmatch(manifest.get("version", "")) or sha256(canonical(logical)) != manifest["version"]:
        raise ValueError("incorrect shared content digest")
    interface, current_version = _core_metadata(addon_root)
    semver = lambda v: tuple(map(int, v.split(".")))
    if not re.fullmatch(r"\d+\.\d+\.\d+", manifest["core_version"]) or semver(current_version) < semver(manifest["core_version"]):
        raise ValueError("core version is incompatible with contributor edition")
    if interface != manifest["interface"]:
        raise ValueError("core interface is incompatible with contributor edition")
    validate_core_source(addon_root, manifest)
    if manifest.get("locale") != "esES" or manifest.get("credit") != "Densuad":
        raise ValueError("unsupported edition locale/credit")
    if set(manifest.get("text_data", {})) != {"entries", "clipHash", "answerHash"} or set(manifest.get("audio_data", {})) != {"clips", "durations"}:
        raise ValueError("unexpected runtime payload fields")
    expected_files = declared_files(manifest)
    expected_inventory = {rel: {"sha256": sha256(blob), "bytes": len(blob)} for rel, blob in expected_files.items()}
    record_ids = set()
    for row in manifest["records"]:
        if not re.fullmatch(r"(?:npc|zone|subzone|topic):[a-z0-9-]+(?:#faq[1-9][0-9]*)?", row["id"]) or row["id"] in record_ids or not row["text"].strip() or sha256(row["text"].encode("utf-8")) != row["script_sha256"]:
            raise ValueError("duplicate record or corrupted exact contributor text")
        record_ids.add(row["id"])
        key, n = split_id(row["id"])
        if row["entry_id"] != key or row["faq_index"] != n or row["kind"] != ("faq_answer_only" if n else "entry_overview"):
            raise ValueError("inconsistent contributor record identity")
        if row["exact_audio_pair"] != (row["recorded_script_sha256"] == row["script_sha256"]):
            raise ValueError("incorrect exact audio pairing flag")
        if not SHA.fullmatch(row["audio_sha256"]) or type(row["audio_bytes"]) is not int or row["audio_bytes"] <= 0 or not math.isfinite(row["duration"]) or row["duration"] <= 0:
            raise ValueError("invalid audio provenance")
        if row["published_audio"]:
            if row["source_status"] != "accepted" or row["recorded_script_sha256"] != row["script_sha256"]:
                raise ValueError("ineligible or wrong-script audio")
            if not re.fullmatch(r"[a-z0-9_-]+\.mp3", row["audio_file"]):
                raise ValueError("unsafe audio member")
            rel = f"{AUDIO_NAME}/Audio/{row['audio_file']}"
            if rel in expected_inventory:
                raise ValueError("duplicate audio member")
            expected_inventory[rel] = {"sha256": row["audio_sha256"], "bytes": row["audio_bytes"]}
    if manifest["files"] != expected_inventory:
        raise ValueError("manifest file inventory differs from declarations")
    expected_names = set(expected_inventory) | {f"{name}/{MANIFEST}" for name in (TEXT_NAME, AUDIO_NAME)}
    actual = set()
    for name, pack in zip((TEXT_NAME, AUDIO_NAME), paths):
        if pack.is_symlink():
            raise ValueError("symlink component")
        for p in pack.rglob("*"):
            if p.is_symlink():
                raise ValueError("symlink in edition")
            if p.is_file():
                actual.add(f"{name}/{p.relative_to(pack).as_posix()}")
    if actual != expected_names:
        raise ValueError("missing or extra contributor pack files")
    for rel, proof in expected_inventory.items():
        p = addon_root / rel
        if p.suffix == ".mp3":
            with p.open("rb") as f:
                if f.read(len(LFS_HEADER)) == LFS_HEADER:
                    raise ValueError("unhydrated LFS audio pointer")
        if p.stat().st_size != proof["bytes"] or file_sha(p) != proof["sha256"]:
            raise ValueError("file bytes/hash mismatch: " + rel)
        if rel in expected_files and p.read_bytes() != expected_files[rel]:
            raise ValueError("Lua or TOC declaration differs from manifest")
    # Exact declared Lua bytes were checked above; execution is unnecessary here.
    # Current source eligibility was audited privately and is bound to core_source.
    current = {key: {"text": entry["source"]["text"], "sp": entry["source"]["sp"],
                      "fp": entry["fp"], "source_sha256": sha256(canonical(entry["source"]))}
               for key, entry in manifest["text_data"]["entries"].items()}
    entries, hashes = manifest["text_data"]["entries"], manifest["text_data"]["clipHash"]
    audio_hashes, durations = manifest["audio_data"]["clips"], manifest["audio_data"]["durations"]
    accepted, published = [], []
    for row in manifest["records"]:
        key, n = split_id(row["id"])
        if row["source_status"] != "accepted":
            if row["id"] in hashes or row["id"] in audio_hashes:
                raise ValueError("deferred record exposed at runtime")
            continue
        accepted.append(row)
        now, entry = current.get(key), entries.get(key)
        if not now or not entry or now["source_sha256"] != row["source_sha256"] or now["fp"] != entry["fp"]:
            raise ValueError("stale underlying English source: " + row["id"])
        if entry.get("source") != {"text": now["text"], "sp": now["sp"]}:
            raise ValueError("incorrect exact underlying English source proof: " + key)
        textrow = next((f for f in entry["faq"] if f["i"] == n), None) if n else entry
        if not textrow or textrow["a" if n else "s"] != row["text"] or textrow["h"] != row["script_sha256"][:6] or hashes.get(row["id"]) != textrow["h"]:
            raise ValueError("missing or incompatible contributed text")
        if n and (textrow["q"] != "" or textrow.get("answerOnly") is not True or textrow["sp"] != now["sp"]["faq"][n - 1]):
            raise ValueError("borrowed question or incorrect original spoiler guard")
        if not n and (entry["n"] != _title(row["text"], key) or entry["sec"] != []):
            raise ValueError("altered overview or invented sections")
        if row["published_audio"]:
            published.append(row)
            if audio_hashes.get(row["id"]) != textrow["h"] or durations.get(row["id"]) != row["duration"]:
                raise ValueError("wrong audio hash or decoded duration")
        elif row["id"] in audio_hashes:
            raise ValueError("unavailable audio declared playable")
    if set(hashes) != {r["id"] for r in accepted} or set(audio_hashes) != {r["id"] for r in published} or set(durations) != set(audio_hashes):
        raise ValueError("extra text/audio declaration")
    if set(entries) != {r["entry_id"] for r in accepted if r["faq_index"] is None}:
        raise ValueError("extra contributed text entry")
    expected_answers = {}
    for key, entry in entries.items():
        faqs = entry["faq"]
        if len({f["i"] for f in faqs}) != len(faqs) or {f["i"] for f in faqs} != {r["faq_index"] for r in accepted if r["entry_id"] == key and r["faq_index"] is not None}:
            raise ValueError("extra or duplicate contributed FAQ")
        if faqs:
            slots = ["000000"] * max(f["i"] for f in faqs)
            for f in faqs:
                slots[f["i"] - 1] = f["h"]
            expected_answers[key] = "".join(slots)
    if manifest["text_data"]["answerHash"] != expected_answers:
        raise ValueError("incorrect original-index answer hashes")
    if manifest["counts"] != _counts(manifest["records"], entries):
        raise ValueError("incorrect declared edition counts")
    if manifest["source_dispositions"] != dict(Counter(r["source_status"] for r in manifest["records"])):
        raise ValueError("incorrect source dispositions")
    return manifest

def build_bundle(addon_root, out_dir, versioned=False):
    """Build one deterministic ZIP containing exactly both validated components."""
    addon_root, out_dir = Path(addon_root), Path(out_dir)
    manifest = validate_pair(addon_root)
    core_metadata = _core_metadata(addon_root)
    if core_metadata[1] != manifest["core_version"]:
        raise ValueError("restamp contributor pair for current core before bundle build")
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = "-" + manifest["core_version"] if versioned else ""
    dest = out_dir / ("LoreForever_Edition_Densuad_esES" + suffix + ".zip")
    names = sorted(set(manifest["files"]) | {f"{n}/{MANIFEST}" for n in (TEXT_NAME, AUDIO_NAME)})
    with tempfile.NamedTemporaryFile(prefix=".contributor-", suffix=".zip", dir=out_dir, delete=False) as f:
        pending = Path(f.name)
    try:
        manifest_proof = {f"{n}/{MANIFEST}": {"sha256": file_sha(addon_root / n / MANIFEST),
                          "bytes": (addon_root / n / MANIFEST).stat().st_size} for n in (TEXT_NAME, AUDIO_NAME)}
        with zipfile.ZipFile(pending, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as z:
            for rel in names:
                info = zipfile.ZipInfo(rel, date_time=(1980, 1, 1, 0, 0, 0))
                info.compress_type, info.create_system, info.external_attr = zipfile.ZIP_DEFLATED, 3, 0o100644 << 16
                info._compresslevel = 9
                digest, size = hashlib.sha256(), 0
                with (addon_root / rel).open("rb") as src, z.open(info, "w") as dst:
                    for block in iter(lambda: src.read(1024 * 1024), b""):
                        digest.update(block)
                        size += len(block)
                        dst.write(block)
                proof = manifest["files"].get(rel, manifest_proof.get(rel))
                if proof != {"sha256": digest.hexdigest(), "bytes": size}:
                    raise ValueError("source changed while building contributor ZIP")
        # A concurrent source/pair update must not publish an artifact checked
        # against the earlier core snapshot, even if every ZIP member matched.
        validate_core_source(addon_root, manifest)
        if _core_metadata(addon_root) != core_metadata:
            raise ValueError("core version/interface changed while building contributor ZIP")
        for name in (TEXT_NAME, AUDIO_NAME):
            current = json.loads((addon_root / name / MANIFEST).read_bytes(), object_pairs_hook=_unique_object)
            if current != manifest:
                raise ValueError("pair changed while building contributor ZIP")
        os.replace(pending, dest)
    finally:
        pending.unlink(missing_ok=True)
    return dest


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--addons", type=Path, default=ROOT / "addon")
    parser.add_argument("--out", type=Path)
    parser.add_argument("--versioned", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.out is None:
            m = validate_pair(args.addons)
            print(json.dumps({"version": m["version"], "counts": m["counts"]}, sort_keys=True))
        else:
            print(build_bundle(args.addons, args.out, args.versioned))
    except (OSError, ValueError, KeyError, TypeError, IndexError) as error:
        parser.exit(1, "contributor-bundle: " + str(error) + "\n")


if __name__ == "__main__":
    main()
