-- Generated by lore.contributor_edition; do not edit.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
P.answerHash = P.answerHash or {}
local t = P.answerHash
t["subzone:camp-narache"] = "fc30247a77b245d14a3376c5"
t["subzone:coldridge-valley"] = "8d0d22f6d572e29d2060ad03"
t["subzone:deathknell"] = "000000492b6dd29a3764fc92"
t["subzone:northshire-abbey"] = "56b216c273bfe9582ea770b9"
t["subzone:shadowglen"] = "1bd6bbd4b5391a17abab4ee0"
t["subzone:valley-of-trials"] = "a91af3b554811feb8087bebd"
t["topic:skyborne"] = "a5c69ecc86528661cbec7ba3d1711c131d49"
t["zone:darnassus"] = "00000059ff2b2e9df5a9aca79f136441cbdf"
t["zone:dunmorogh"] = "73a334637710b4489a65db3633317be67911"
t["zone:elwynn"] = "e687329f68a62d27bce7e49722d611185114"
t["zone:ironforge"] = "8ff9bf812ba5be1e36f12be7c1bd84f7a0c0"
t["zone:orgrimmar"] = "b6a4313623a79d1b098afc82f444025a5ae5"
t["zone:stormwind"] = "69130d0d48390db8b093558e0190e7965943202320"
t["zone:teldrassil"] = "efcbd24fa4be8606e33078e5b6c98ee4b484"
t["zone:thunderbluff"] = "88e03e7ba860540aaa56aacf5b3399b1a11f"
t["zone:tirisfal"] = "f897123f7e16735aa6e00e6da08edf0f197d"
t["zone:undercity"] = "f1e09eebed60cf0afe8b3ccd30d525286722"
t["zone:zephras"] = "63fcac97c336d234f884b808eb77021f8ee4"
