-- Generated by lore.contributor_edition; do not edit.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
P.clipHash = P.clipHash or {}
local t = P.clipHash
t["zone:zephras#faq5"] = "eb7702"
t["zone:zephras#faq6"] = "1f8ee4"
