-- Generated by lore.contributor_edition; do not edit.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
P.edition = {["api"]=1,["id"]="densuad-esES",["peer"]="LoreForever_Edition_Densuad_esES_Audio",["version"]="5031fe1e462b0efb2495cb9282a6e53d8498a1c1234a54fcbc81fdab834f12b4"}
