-- Generated by lore.contributor_edition; do not edit.
local name = ...
local P = LoreForeverPacks and LoreForeverPacks.Begin(name)
if not P then return end
P.edition = {["api"]=1,["id"]="densuad-esES",["peer"]="LoreForever_Edition_Densuad_esES_Audio",["version"]="08a39ee92b88d5fe3435aa96aacc501ed37eea159ff48e3aeccffadb351d3b8f"}
